apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db2
spec:
  ports:
    - port: 5432
  selector:
    app: db2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
spec:
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: curso_springboot
            - name: POSTGRES_USER
              value: devdb
            - name: POSTGRES_PASSWORD
              value: a1b2c3d4
            - name: PGDATA
              value: /var/lib/postgresql/data/db
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db2-storage
      volumes:
        - name: db2-storage
          persistentVolumeClaim:
            claimName: db2-pvc